### ISSUE TITLE
export .mat to .xml

### ISSUE THREAD

**Issue by zoey-rw** [pwendering/COMMIT#2]
Hi, thanks for publishing this excellent collection of consensus models. I'm trying to load the soil models into Python, after separating the merged file into separate mat files using this snippet:
```
load('data/models/consensus/Soil_consensus_models_biomass')
experiments = {'Schlaeppi','Bulgarelli'};
i = 1 
% write single .mat files for every model in a subdirectory
tmpModelDir = fullfile(modelDir, 'tmp_models', [experiments{i}, tmp_spec]);
[s, fileList] = createModelDir(merged_models, tmpModelDir);
```
However, I cannot figure out how to convert the separated .mat files to .xml. For example, I tried the following for Soil522.mat:
- from Matlab/cobra, `readCbModel` returns `Error using readCbModel (line 112)
Cannot process this file type` when the .mat file is selected interactively
- from python: `cobra.io.load_matlab_model` returns `ValueError: Names cannot contain whitespace characters. "n 1-4-alpha-D-Glucan[c]" contains whitespace character " ". `  
- from R (to remove whitespace from names): `R.matlab::writeMat` freezes without writing

Do you have any code recommendations for exporting the files as SBML for use in Python (ideally with the MetaNetX namespace)? Thanks in advance!

**Comment by pwendering** [comment]
Hi Zoey,
thanks for your interest in the consensus models.

I could unfortunately not reproduce your error in Matlab. At `code/matlab/gap_filling_analysis/write_models_sbml.m` you can find the script that I used to write the gap-filled reconstructions in SBML format.

I added a branch [enh/sbml_export](/pwendering/commit/tree/enh/sbml_export) that includes an updated version of this script, `write_models_sbml_raw.m` at the same location. It loads the soil consensus reconstructions (before gap filling), replaces white spaces with underscores in metabolite and reaction identifiers, and writes them to sbml files.

This should resolve the error that you got while reading the models from Python cobra.

I hope this resolves your problem! Let me know if you encounter further problems.

**Comment by zoey-rw** [comment]
Thanks so much for your help! I was actually able to get the `code/matlab/gap_filling_analysis/write_models_sbml.m` script running once I updated my version of Matlab's cobratoolbox, and now they are importing successfully in Python - sorry for the trouble.

A related question (but we can migrate this to a new Issue if you prefer): your paper mentions adding transport reactions from cytosol to extracellular space when necessary. But the SBML models (whether from `write_models_sbml.m` or `write_models_sbml_raw.m`) only have one compartment, cytosol (though some of the metabolite names still have the "[e]" suffix). Do you know if the lack of an extracellular compartment is an exporting error, or was it necessary/intentional?

**Comment by pwendering** [comment]
Excellent! I am glad it worked. I will close this issue so we can discuss the other question in a separate issue.
